module.exports = {
  appearance: ['responsive'],
  backgroundAttachment: ['responsive'],
  backgroundColors: ['responsive', 'hover', 'focus'],
  backgroundPosition: ['responsive'],
  backgroundRepeat: ['responsive'],
  backgroundSize: ['responsive'],
  borderCollapse: [],
  borderColors: ['responsive', 'hover', 'focus'],
  borderRadius: ['responsive', 'important'],
  borderStyle: ['responsive'],
  borderWidths: ['responsive'],
  cursor: ['responsive'],
  display: ['responsive'],
  flexbox: ['responsive'],
  float: ['responsive'],
  fonts: ['responsive'],
  fontWeights: ['responsive', 'hover', 'focus'],
  height: ['responsive'],
  leading: ['responsive'],
  lists: ['responsive'],
  margin: ['responsive'],
  maxHeight: ['responsive'],
  maxWidth: ['responsive'],
  minHeight: ['responsive'],
  minWidth: ['responsive'],
  negativeMargin: ['responsive'],
  opacity: ['responsive'],
  outline: ['focus'],
  overflow: ['responsive'],
  padding: ['responsive'],
  pointerEvents: ['responsive'],
  position: ['responsive'],
  resize: ['responsive'],
  shadows: ['responsive', 'hover', 'focus'],
  svgFill: [],
  svgStroke: [],
  tableLayout: ['responsive'],
  textAlign: ['responsive'],
  textColors: ['responsive', 'hover', 'focus', 'important'],
  textSizes: ['responsive'],
  textStyle: ['responsive', 'hover', 'focus'],
  tracking: ['responsive'],
  userSelect: ['responsive'],
  verticalAlign: ['responsive'],
  visibility: ['responsive'],
  whitespace: ['responsive'],
  width: ['responsive'],
  zIndex: ['responsive'],
  objectFit: ['responsive'],
};
